# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Set the working directory.
WORKDIR /app

# Install the application dependencies.
COPY ./uv.lock ./pyproject.toml ./
RUN uv sync --frozen --no-cache

# Copy the data_cdc and core directories
COPY ./src ./

ENV PYTHONPATH=/app

# CMD ["uv", "run", "python", "/app/data_cdc/cdc.py"]
CMD uv run python /app/data_cdc/cdc.py && tail -f /dev/null
